routes/web.php
<?php
Route::redirect('/', '/admin/home');

Auth::routes(['register' => false]);

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::delete('permissions_mass_destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.mass_destroy');

    Route::resource('roles', 'Admin\RolesController');
    Route::delete('roles_mass_destroy', 'Admin\RolesController@massDestroy')->name('roles.mass_destroy');

    Route::resource('users', 'Admin\UsersController');
    Route::delete('users_mass_destroy', 'Admin\UsersController@massDestroy')->name('users.mass_destroy');

    Route::resource('keys', 'Admin\KeyToolController');
    Route::delete('keys_mass_destroy', 'Admin\KeyToolController@massDestroy')->name('keys.mass_destroy');

    Route::resource('accounts', 'Admin\AccountListController');
    Route::delete('accounts_mass_destroy', 'Admin\AccountListController@massDestroy')->name('accounts.mass_destroy');
});

resources/views/admin/keys/create.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card">
        <div class="card-header">
            {{ trans('global.create') }} {{ trans('cruds.key_tool.title_singular') }}
        </div>

        <div class="card-body">
            <form action="{{ route("admin.keys.store") }}" method="POST" enctype="multipart/form-data">
                @method('POST')
                @csrf
                <div class="form-group {{ $errors->has('machine_name') ? 'has-error' : '' }}">
                    <label for="machine_name">{{ trans('cruds.key_tool.fields.machine_name') }}*</label>
                    <input type="text" id="machine_name" name="machine_name" class="form-control" value="{{ old('machine_name', isset($keys) ? $keys->machine_name : '') }}" required>
                    @if($errors->has('machine_name'))
                        <em class="invalid-feedback">
                            {{ $errors->first('machine_name') }}
                        </em>
                    @endif
                    <p class="helper-block">
                        {{ trans('cruds.key_tool.fields.machine_name_helper') }}
                    </p>
                </div>
                <div class="form-group {{ $errors->has('key') ? 'has-error' : '' }}">
                    <label for="key">{{ trans('cruds.key_tool.fields.key') }}*</label>
                    <input type="text" id="key" name="key" class="form-control" value="{{ old('key', isset($keys) ? $keys->key : '') }}" required>
                    @if($errors->has('key'))
                        <em class="invalid-feedback">
                            {{ $errors->first('key') }}
                        </em>
                    @endif
                    <p class="helper-block">
                        {{ trans('cruds.key_tool.fields.key_helper') }}
                    </p>
                </div>
                <div class="form-group {{ $errors->has('user_id') ? 'has-error' : '' }}">
                    <label for="user_id">{{ trans('cruds.key_tool.fields.user') }}*</label>
                    <select class="form-control" name="user_id">
                        @foreach($users as $user)
                            <option value="{{ $user->id }}">{{ $user->name }}</option>
                        @endforeach
                    </select>
                    @if($errors->has('user_id'))
                        <em class="invalid-feedback">
                            {{ $errors->first('user_id') }}
                        </em>
                    @endif
                    <p class="helper-block">
                        {{ trans('cruds.key_tool.fields.user_helper') }}
                    </p>
                </div>
                <div class="form-group {{ $errors->has('is_active') ? 'has-error' : '' }}">
                    <label for="is_active">{{ trans('cruds.key_tool.fields.is_active.name') }}*</label>
                    <select class="form-control" name="is_active">
                        <option value="1">{{ trans('cruds.key_tool.fields.is_active.1') }}</option>
                        <option value="0">{{ trans('cruds.key_tool.fields.is_active.0') }}</option>
                    </select>
                    @if($errors->has('is_active'))
                        <em class="invalid-feedback">
                            {{ $errors->first('is_active') }}
                        </em>
                    @endif
                </div>
                <div class="form-group {{ $errors->has('expired_at') ? 'has-error' : '' }}">
                    <label for="is_active">{{ trans('cruds.key_tool.fields.expired_at') }}*</label>
                    <input class="form-control" id="expired_at" type="date" name="expired_at" placeholder="date">
                    @if($errors->has('expired_at'))
                        <em class="invalid-feedback">
                            {{ $errors->first('expired_at') }}
                        </em>
                    @endif
                    <p class="helper-block">
                        {{ trans('cruds.key_tool.fields.expired_at_helper') }}
                    </p>
                </div>

                <div>
                    <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/keys/edit.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card">
        <div class="card-header">
            {{ trans('global.create') }} {{ trans('cruds.key_tool.title_singular') }}
        </div>

        <div class="card-body">
            <form action="{{ route("admin.keys.update", $key->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group {{ $errors->has('machine_name') ? 'has-error' : '' }}">
                    <label for="machine_name">{{ trans('cruds.key_tool.fields.machine_name') }}*</label>
                    <input type="text" id="machine_name" name="machine_name" class="form-control" value="{{ old('machine_name', isset($key) ? $key->machine_name : '') }}" required>
                    @if($errors->has('machine_name'))
                        <em class="invalid-feedback">
                            {{ $errors->first('machine_name') }}
                        </em>
                    @endif
                    <p class="helper-block">
                        {{ trans('cruds.key_tool.fields.machine_name_helper') }}
                    </p>
                </div>
                <div class="form-group {{ $errors->has('key') ? 'has-error' : '' }}">
                    <label for="key">{{ trans('cruds.key_tool.fields.key') }}*</label>
                    <input type="text" id="key" name="key" class="form-control" value="{{ old('key', isset($key) ? $key->key : '') }}" required>
                    @if($errors->has('key'))
                        <em class="invalid-feedback">
                            {{ $errors->first('key') }}
                        </em>
                    @endif
                    <p class="helper-block">
                        {{ trans('cruds.key_tool.fields.key_helper') }}
                    </p>
                </div>
                <div class="form-group {{ $errors->has('user_id') ? 'has-error' : '' }}">
                    <label for="user_id">{{ trans('cruds.key_tool.fields.user') }}*</label>
                    <select class="form-control" name="user_id">
                        @foreach($users as $user)
                            <option value="{{ $user->id }}" @if($key->user_id ==$user->id ) selected @endif>{{ $user->name }}</option>
                        @endforeach
                    </select>
                    @if($errors->has('user_id'))
                        <em class="invalid-feedback">
                            {{ $errors->first('user_id') }}
                        </em>
                    @endif
                    <p class="helper-block">
                        {{ trans('cruds.key_tool.fields.user_helper') }}
                    </p>
                </div>
                <div class="form-group {{ $errors->has('is_active') ? 'has-error' : '' }}">
                    <label for="is_active">{{ trans('cruds.key_tool.fields.is_active.name') }}*</label>
                    <select class="form-control" name="is_active">
                        <option value="1" @if($key->is_active == App\Enums\KeyToolStatus::Activated ) selected @endif>{{ trans('cruds.key_tool.fields.is_active.1') }}</option>
                        <option value="0"  @if($key->is_active == App\Enums\KeyToolStatus::DeActivated ) selected @endif>{{ trans('cruds.key_tool.fields.is_active.0') }}</option>
                    </select>
                    @if($errors->has('is_active'))
                        <em class="invalid-feedback">
                            {{ $errors->first('is_active') }}
                        </em>
                    @endif
                </div>
                <div class="form-group {{ $errors->has('expired_at') ? 'has-error' : '' }}">
                    <label for="is_active">{{ trans('cruds.key_tool.fields.expired_at') }}*</label>
                    <input class="form-control" id="expired_at" type="date" name="expired_at"  value="{{ \Carbon\Carbon::parse($key->expired_at)->format('m/d/Y')}}">
                    @if($errors->has('expired_at'))
                        <em class="invalid-feedback">
                            {{ $errors->first('expired_at') }}
                        </em>
                    @endif
                    <p class="helper-block">
                        {{ trans('cruds.key_tool.fields.expired_at_helper') }}
                    </p>
                </div>

                <div>
                    <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/keys/index.blade.php
@extends('layouts.admin')
@section('content')
    @can('keys_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route("admin.keys.create") }}">
                    {{ trans('global.add') }} {{ trans('cruds.key_tool.title_singular') }}
                </a>
            </div>
        </div>
    @endcan
    <div class="card">
        <div class="card-header">
            {{ trans('cruds.key_tool.title_singular') }} {{ trans('global.list') }}
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class=" table table-bordered table-striped table-hover datatable datatable-User">
                    <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.key_tool.fields.key') }}
                        </th>
                        <th>
                            {{ trans('cruds.key_tool.fields.machine_name') }}
                        </th>
                        <th>
                            {{ trans('cruds.key_tool.fields.expired_at') }}
                        </th>
                        <th>
                            {{ trans('cruds.key_tool.fields.status') }}
                        </th>
                        <th>
                            &nbsp; {{ trans('global.actions') }}
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($keys as $key => $item)
                        <tr data-entry-id="{{ $item->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $item->key ?? '' }}
                            </td>
                            <td>
                                {{ $item->machine_name ?? '' }}
                            </td>
                            <td>
                                {{ $item->expired_at ?? '' }}
                            </td>
                            <td>
                                {{ $item->status ?? '' }}
                            </td>

                            <td>
                                @can('keys_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.keys.show', $item->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan
                                @can('keys_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.keys.edit', $item->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan
                                @can('keys_delete')
                                    <form action="{{ route('admin.keys.destroy', $item->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>


        </div>
    </div>
@endsection
@section('scripts')
    @parent
    <script>
        $(function () {
            let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
            @can('keys_delete')
            let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
            let deleteButton = {
                text: deleteButtonTrans,
                url: "{{ route('admin.keys.mass_destroy') }}",
                className: 'btn-danger',
                action: function (e, dt, node, config) {
                    var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
                        return $(entry).data('entry-id')
                    });

                    if (ids.length === 0) {
                        alert('{{ trans('global.datatables.zero_selected') }}')

                        return
                    }

                    if (confirm('{{ trans('global.areYouSure') }}')) {
                        $.ajax({
                            headers: {'x-csrf-token': _token},
                            method: 'POST',
                            url: config.url,
                            data: { ids: ids, _method: 'DELETE' }})
                            .done(function () { location.reload() })
                    }
                }
            }
            dtButtons.push(deleteButton)
            @endcan
            $.extend(true, $.fn.dataTable.defaults, {
                order: [[ 1, 'desc' ]],
                pageLength: 100,
            });
            $('.datatable-User:not(.ajaxTable)').DataTable({ buttons: dtButtons })
            $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
                $($.fn.dataTable.tables(true)).DataTable()
                    .columns.adjust();
            });
        })

    </script>
@endsection

resources/views/admin/keys/show.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card">
        <div class="card-header">
            {{ trans('cruds.key_tool.title_singular') }}: {{ $key->key }}
        </div>
        <div class="card-body">
            <div class="row mb-4">
                <div class="col-sm-4">
                    <h6 class="mb-3"> {{ trans('global.infomations') }}:</h6>
                    <div><strong>{{ trans('cruds.key_tool.title_singular') }}:</strong> {{ $key->key }}</div>
                    <div><strong>{{ trans('cruds.key_tool.fields.created_at') }}:</strong> {{ $key->created_at }}</div>
                    <div><strong>{{ trans('cruds.key_tool.fields.machine_name') }}:</strong> {{ $key->machine_name }}</div>
                    <div><strong>{{ trans('cruds.key_tool.fields.user') }}:</strong> {{ $key->user->name }}</div>
                    <div><strong>{{ trans('cruds.key_tool.fields.is_active.name') }}:</strong> {{ trans('cruds.key_tool.fields.is_active.'.$key->is_active ) }}</div>
                </div>

                <div class="col-sm-4">
                    <h6 class="mb-3">{{ trans('global.statistics') }}:</h6>
                    <div><strong>Account:</strong> {{ $key->accounts->count() }}</div>
                </div>

            </div>
            @can('accounts_manage')
            <div class="table-responsive-sm">
                <table class="table table-bordered table-striped table-hover datatable datatable-User">
                    <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th class="center">{{ trans('cruds.account.fields.id') }}</th>
                        <th>{{ trans('cruds.account.fields.name') }}</th>
                        <th>{{ trans('cruds.account.fields.server') }}</th>
                        <th class="center">{{ trans('cruds.account.fields.planet') }}</th>
                        <th class="right">{{ trans('cruds.account.fields.power') }}</th>
                        <th class="right">{{ trans('cruds.account.fields.gem') }}</th>
                        <th class="right">{{ trans('cruds.account.fields.missions') }}</th>
                        <th class="right">{{ trans('cruds.account.fields.map') }}</th>
                        <th class="right">{{ trans('cruds.account.fields.login_at') }}</th>
                        <th class="right">{{ trans('cruds.account.fields.status') }}</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach($key->accounts as $account)
                            <tr data-entry-id="{{ $account->id }}">
                             <td></td>
                             <td>{{ $account->id }}</td>
                             <td>{{ $account->name }}</td>
                             <td>{{ $account->server }}</td>
                             <td>{{ $account->planet }}</td>
                             <td>{{ $account->power }}</td>
                             <td>{{ $account->gem }}</td>
                             <td>{{ $account->missions }}</td>
                             <td>{{ $account->map }}</td>
                             <td>{{ $account->login_at }}</td>
                             <td>{{ $account->status }}</td>
                         </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            @endcan
        </div>
    </div>
@endsection
@section('scripts')
    @parent
    <script>
        $(function () {
            let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
           @can('accounts_delete')
            let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
            let deleteButton = {
                text: deleteButtonTrans,
                url: "{{ route('admin.accounts.mass_destroy') }}",
                className: 'btn-danger',
                action: function (e, dt, node, config) {
                    var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
                        return $(entry).data('entry-id')
                    });

                    if (ids.length === 0) {
                        alert('{{ trans('global.datatables.zero_selected') }}')

                        return
                    }

                    if (confirm('{{ trans('global.areYouSure') }}')) {
                        $.ajax({
                            headers: {'x-csrf-token': _token},
                            method: 'POST',
                            url: config.url,
                            data: { ids: ids, _method: 'DELETE' }})
                                .done(function () { location.reload() })
                    }
                }
            }
            dtButtons.push(deleteButton)
            @endcan
            $.extend(true, $.fn.dataTable.defaults, {
                order: [[ 1, 'desc' ]],
                pageLength: 100,
            });
            $('.datatable-User:not(.ajaxTable)').DataTable({ buttons: dtButtons })
            $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
                $($.fn.dataTable.tables(true)).DataTable()
                        .columns.adjust();
            });
        })

    </script>
@endsection